version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# index files
- url: (/|/demo)
  static_files: static/index.html
  upload: static/index.html
  http_headers:
    Access-Control-Allow-Origin: https://accounts.google.com
- url: /
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: https://accounts.google.com